FROM jenkins/jenkins:lts-jdk17

USER root
RUN apt-get update \
 && apt-get install -y docker.io docker-compose-plugin \
 && rm -rf /var/lib/apt/lists/*

RUN groupadd -for docker && usermod -aG docker jenkins

USER jenkins